title: "Cuaderno"
author: "HC"
description: ""
url: "http://haztecaso.mooo.com"
baseurl: "/blog"
lang: "es"

excerpt_separator: <!--more-->

plugins: [jekyll-paginate]

permalink: /blog/:title/
paginate_pathds: /blog/:num/
paginate: 5

exclude: [notes.md]
