title: "Cuaderno"
author: "HC"
description: ""
url: "http://haztecaso.mooo.com"
baseurl: "/blog"
lang: "es"

plugins: [jekyll-paginate]
markdown: CommonMarkGhPages

permalink: /blog/:title/
paginate_pathds: /blog/:num/
paginate: 5

exclude: [notes.md]
